version: "3.8"
services:
  web:
    # build: .
    image: elixir:latest
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
    # env_file:
    #   - some_app.env

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
